# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('propietarios', '0001_initial'),
        ('ciudades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='alquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=150)),
                ('metros', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('habitaciones', models.IntegerField()),
                ('descripccion', models.CharField(max_length=300)),
                ('opcion', models.CharField(max_length=2)),
                ('disponibilidad', models.BooleanField()),
                ('alqui', models.ManyToManyField(blank=True, through='inmuebles.alquiler', to='clientes.Cliente')),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ciudades.Ciudad')),
                ('comprar', models.ManyToManyField(blank=True, related_name='comprar', to='clientes.Cliente')),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propietarios.Propietario')),
            ],
        ),
        migrations.AddField(
            model_name='alquiler',
            name='inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmuebles.Inmueble'),
        ),
    ]
